### ISSUE TITLE
"hidden tab" seems to never work

### ISSUE THREAD

**Issue by Xepherxv** [SoundControl/Issues#53] opened 2013-07-11 04:54 UTC
well the title pretty much explains it. ive only gotten the hidden tab to work ONCE. ive used this for 5 days now. opening in pinned or full works fine.

**Comment by SoundControl** [comment] 2013-07-11 05:04
Can you clarify what you mean by not "working"? What happens? Have you
waited at least 10sec? What version of SC, Chrome, and computer OS are you
using?

**Comment by Xepherxv** [comment] 2013-07-11 05:08
It dosent do anything. the player acts as if theres no tab open of pandora
yes i have waited ten seconds.
i dont know what SC means (sorry) but im using a windows XP: media center
edition 32 bit and im using chrome:28.0.1500.71 m

**Comment by SoundControl** [comment] 2013-07-11 05:26
I meant SoundControl when I said SC -- I assume you have the newest version
1.0.2

Unfortunately, that isn't much to go on. If the hidden tab isn't working it
should automatically open a visible tab. Does pandora break when you have
it open normally? Do you see a message that SoundControl has crashed? Do
you have volume turned on?.. I might suggest changing your version of flash.

**Comment by Xepherxv** [comment] 2013-07-11 05:31
then yes i have the newest version, it does not automaticly open a pandora
tab (i usally open it myself) and it is not prone to breaking unless flash
crahses whitch usally only happens when i have too many youtube tabs open
whits isint the case in this. and my volume is defenalty turned on ;P
thanks for your help :D

**Comment by SoundControl** [comment] 2013-09-11 08:11
I can't reproduce this and haven't received any similar reports, so closing

**Closed as completed by SoundControl** 2013-09-11 08:11 UTC
Labels: bug
