### ISSUE TITLE
Pandora doesn't auto-pause when playing a youtube video

### ISSUE THREAD

**Issue by jarquafelmu** [SoundControl/Issues#107] opened 2014-02-02 21:28 UTC
My pandora isn't auto-pausing when playing a youtube video. I use SoundControl Plus version 1.6.1.

What information do you need to help track down the issue? I don't know how to recreate it.

**Comment by SoundControl** [comment] 2014-02-02 22:20
Is the YouTube player on YouTube.com or another site?

**Comment by jarquafelmu** [comment] 2014-02-03 07:02
It was the video was on youtube.com directly and at first I noticed that my
soundcontrol wasn't donfigured to interact with youtube so I enabled that
and it worked for one video after then stopped autopausing again.
- Samuel Terrazas
  "Be true to yourself, then be true to others".

**Comment by SoundControl** [comment] 2014-02-03 15:27
So it is working correctly now? Please let me know if the issue happens
again.

**Comment by jarquafelmu** [comment] 2014-02-04 00:35
The problem still happens
- Samuel Terrazas
  "Be true to yourself, then be true to others".

**Comment by SoundControl** [comment] 2014-02-04 01:22
I've found an issue similar to what you have described. It will be fixed in
the next update. Please let me know if the issue is still happening in a
couple days.

--Scott

**Comment by SoundControl** [comment] 2014-02-20 21:17
I've fixed a similar bug

**Closed as completed by SoundControl** 2014-02-20 21:17 UTC
Labels: bug
